import { SignIn, SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import { api } from "~/utils/api";

const Home: NextPage = () => {

  const user = useUser();

  const { data, isLoading } = api.posts.getAll.useQuery();

  if (isLoading) return <div className="flex justify-center items-center h-screen">
    <div className="text-slate-400">
      Loading...
    </div>
  </div>;

  if (!data) return <div className="flex justify-center items-center h-screen">
    <div className="text-slate-400">
      Something went wrong...
    </div>
  </div>;

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-center h-screen">
        <div className="h-full w-full md:max-w-2xl border-x border-stone-500">
          <div className="flex border-b border-stone-500 text-slate-300 p-4">{!user.isSignedIn && <div className="flex justify-center"><SignInButton /></div>}{!!user.isSignedIn && <SignOutButton />}</div>
          <div className="flex flex-col text-slate-400">
            {data?.map((post) => (<div key={post.id} className="p-8  border-b border-stone-500">{post.content}</div>
            ))}
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
